// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVFAExz1ONuKQPUMRPCep16fT0WGPKxc',
    appId: '1:965584796909:web:768483f83bacb27c33e0e4',
    messagingSenderId: '965584796909',
    projectId: 'crud-6f763',
    authDomain: 'crud-6f763.firebaseapp.com',
    storageBucket: 'crud-6f763.appspot.com',
    measurementId: 'G-B4FM3C7JM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0ylPmGqjnhsxHy1Vdabf2pQyNGSN_do',
    appId: '1:965584796909:android:989bd83672b1ccbf33e0e4',
    messagingSenderId: '965584796909',
    projectId: 'crud-6f763',
    storageBucket: 'crud-6f763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFu8z9Rv8PTgs18yAmfIbMNNWweR0lhE',
    appId: '1:965584796909:ios:1e0a15466c6a373733e0e4',
    messagingSenderId: '965584796909',
    projectId: 'crud-6f763',
    storageBucket: 'crud-6f763.appspot.com',
    iosClientId: '965584796909-au02tul2jgl8f92gdo2qltnejm669vp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFu8z9Rv8PTgs18yAmfIbMNNWweR0lhE',
    appId: '1:965584796909:ios:1e0a15466c6a373733e0e4',
    messagingSenderId: '965584796909',
    projectId: 'crud-6f763',
    storageBucket: 'crud-6f763.appspot.com',
    iosClientId: '965584796909-au02tul2jgl8f92gdo2qltnejm669vp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
